import os from "os";
import path from "path";
import fs from "fs";
import { exec } from "child_process";
import { promisify } from "util";
import { logger, prisma } from "../../config";
import { cloneRepo } from "../../services/github";
import { frameWithFastlane } from "../../services/frame-screenshots";

const execAsync = promisify(exec);

export async function runScreenshotGeneration(jobId: string): Promise<void> {
  const job = await prisma.screenshotJob.findUnique({
    where: { id: jobId },
    include: { app: true },
  });
  if (!job) throw new Error(`Screenshot job ${jobId} not found`);

  const logs: string[] = [];
  const log = (msg: string) => {
    logs.push(msg);
    logger.info(`[screenshots:${jobId}] ${msg}`);
  };

  await prisma.screenshotJob.update({
    where: { id: jobId },
    data: { status: "RUNNING", startedAt: new Date() },
  });

  const tmpDir = path.join(os.tmpdir(), `appcore-screenshots-${jobId}`);
  const outputDir = path.join(process.cwd(), "screenshots", jobId);

  try {
    // 1. Get a user with a GitHub token to use for cloning the repo
    const userWithToken = await prisma.userSettings.findFirst({
      where: { githubAccessToken: { not: null } },
    });

    if (!userWithToken?.githubAccessToken) {
      throw new Error("No GitHub access token available");
    }

    if (!job.app.githubRepoFullName) {
      throw new Error("No GitHub repo linked to this app");
    }

    // 2. Clone the repo
    log(`Cloning ${job.app.githubRepoFullName}@${job.branch ?? "default"} ...`);
    await cloneRepo(
      userWithToken.githubAccessToken,
      job.app.githubRepoFullName,
      tmpDir,
      job.branch ?? undefined,
    );
    log("Clone complete");

    // 3. Check if Snapfile or Fastfile exists
    const snapfilePath = path.join(tmpDir, "fastlane", "Snapfile");
    const fastfilePath = path.join(tmpDir, "fastlane", "Fastfile");
    const hasSnapfile = fs.existsSync(snapfilePath);
    const hasFastfile = fs.existsSync(fastfilePath);

    if (!hasSnapfile && !hasFastfile) {
      log(
        "No fastlane/Snapfile or fastlane/Fastfile found — creating default Snapfile",
      );
      const fastlaneDir = path.join(tmpDir, "fastlane");
      fs.mkdirSync(fastlaneDir, { recursive: true });
      fs.writeFileSync(
        snapfilePath,
        [
          "# Auto-generated by AppCore",
          `# App: ${job.app.name} (${job.app.bundleId})`,
          "",
          "devices([",
          '  "iPhone 16 Pro Max",',
          '  "iPhone 16",',
          '  "iPad Pro 13-inch (M4)"',
          "])",
          "",
          'languages(["en-US"])',
          "",
          'scheme("CityTailor")',
          "",
          "clear_previous_screenshots(true)",
          `output_directory("./fastlane/screenshots")`,
          "",
        ].join("\n"),
      );
    }

    // 4. Patch UITest Swift files to fix Swift 6 @MainActor concurrency errors.
    patchUITestFiles(tmpDir, log);

    const fastlanePath = await findFastlane();
    log(`Using fastlane: ${fastlanePath}`);

    // 5. Run `fastlane snapshot`
    log("Running fastlane snapshot ...");
    try {
      const { stdout, stderr } = await execAsync(
        `${fastlanePath} snapshot 2>&1`,
        {
          cwd: tmpDir,
          timeout: 600_000,
          env: { ...process.env, FASTLANE_DISABLE_COLORS: "1" },
          maxBuffer: 10 * 1024 * 1024,
        },
      );

      if (stdout) logs.push(...stdout.split("\n").filter(Boolean));
      if (stderr) {
        const errLines = stderr.split("\n").filter(Boolean);
        errLines.forEach((l) => logs.push(`[stderr] ${l}`));
      }
    } catch (execErr: any) {
      if (execErr.stdout) {
        logs.push(...execErr.stdout.split("\n").filter(Boolean));
      }
      if (execErr.stderr) {
        logs.push(...execErr.stderr.split("\n").filter(Boolean));
      }
      throw new Error(
        `fastlane snapshot exited with code ${execErr.code ?? "unknown"}. ` +
          `Last output: ${(execErr.stderr || execErr.stdout || "").slice(-500)}`,
      );
    }

    log("fastlane snapshot completed");

    // 6. Copy generated screenshots to persistent output dir
    const screenshotsDir = path.join(tmpDir, "fastlane", "screenshots");
    const screenshotUrls: string[] = [];

    if (fs.existsSync(screenshotsDir)) {
      const copyFiles = (src: string, dest: string) => {
        fs.mkdirSync(dest, { recursive: true });
        for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
          const srcPath = path.join(src, entry.name);
          const destPath = path.join(dest, entry.name);
          if (entry.isDirectory()) {
            copyFiles(srcPath, destPath);
          } else if (/\.(png|jpg|jpeg)$/i.test(entry.name)) {
            fs.copyFileSync(srcPath, destPath);
            screenshotUrls.push(destPath);
          }
        }
      };
      copyFiles(screenshotsDir, outputDir);
      log(`Saved ${screenshotUrls.length} screenshot(s) to ${outputDir}`);
    } else {
      log("No screenshots directory found after run");
    }

    // 7. Update job as completed
    await prisma.screenshotJob.update({
      where: { id: jobId },
      data: {
        status: "COMPLETED",
        completedAt: new Date(),
        logs: JSON.stringify(logs),
        screenshotUrls,
      },
    });

    // 8. Auto-frame screenshots
    try {
      const screenshotsBase = path.join(process.cwd(), "screenshots");
      const framedDir = path.join(outputDir, "framed");
      const subDirs = fs.existsSync(outputDir)
        ? fs
            .readdirSync(outputDir, { withFileTypes: true })
            .filter((e) => e.isDirectory() && e.name !== "framed")
            .map((e) => path.join(outputDir, e.name))
        : [];
      const sourceDirs = subDirs.length > 0 ? subDirs : [outputDir];
      const framedByLocale: Record<string, string[]> = {};

      for (const srcDir of sourceDirs) {
        const rel = path.relative(outputDir, srcDir);
        const locale = path.basename(srcDir);
        const outDir = path.join(framedDir, rel === "." ? "" : rel);
        const outputPaths = await frameWithFastlane(srcDir, outDir, {
          subtitle: job.app.name,
        });
        const urls = outputPaths.map(
          (p) =>
            "/screenshots/" +
            path.relative(screenshotsBase, p).replace(/\\/g, "/"),
        );
        const key = rel === "." ? "default" : locale;
        framedByLocale[key] = (framedByLocale[key] ?? []).concat(urls);
      }

      await prisma.screenshotJob.update({
        where: { id: jobId },
        data: { framedByLocale: framedByLocale } as any,
      });
      log(`Auto-framing complete: ${Object.values(framedByLocale).flat().length} image(s)`);
    } catch (frameErr: any) {
      log(`Auto-framing failed (non-fatal): ${frameErr.message}`);
      // Don't fail the job — screenshots are still saved
    }
  } catch (err: any) {
    const msg = err instanceof Error ? err.message : String(err);
    logs.push(`ERROR: ${msg}`);

    await prisma.screenshotJob.update({
      where: { id: jobId },
      data: {
        status: "FAILED",
        error: msg,
        completedAt: new Date(),
        logs: JSON.stringify(logs),
      },
    });
  } finally {
    // Cleanup
    try {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    } catch {
      // ignore
    }
  }
}

function patchUITestFiles(repoDir: string, log: (msg: string) => void): void {
  const findSwift = (dir: string, results: string[] = []): string[] => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory() && !entry.name.startsWith(".")) {
        findSwift(full, results);
      } else if (entry.isFile() && entry.name.endsWith(".swift")) {
        results.push(full);
      }
    }
    return results;
  };

  const swiftFiles = findSwift(repoDir);
  for (const file of swiftFiles) {
    const src = fs.readFileSync(file, "utf8");
    if (!src.includes("setupSnapshot(")) continue;

    const patched = src.replace(
      /^(?!.*@MainActor\b)([ \t]*)((?:final\s+)?class\s+\w+\s*:\s*XCTestCase)/gm,
      (_match, indent, classDecl) =>
        `${indent}@MainActor\n${indent}${classDecl}`,
    );

    if (patched !== src) {
      fs.writeFileSync(file, patched, "utf8");
      log(
        `Patched @MainActor onto UITest class in ${path.relative(repoDir, file)}`,
      );
    }
  }
}

async function findFastlane(): Promise<string> {
  const candidates = [
    "fastlane",
    "/usr/local/bin/fastlane",
    `${os.homedir()}/.fastlane/bin/fastlane`,
  ];
  for (const c of candidates) {
    try {
      await execAsync(`${c} --version`);
      return c;
    } catch {
      // next
    }
  }
  try {
    await execAsync("bundle exec fastlane --version");
    return "bundle exec fastlane";
  } catch {
    // not available
  }
  throw new Error(
    "Fastlane not found. Install via `brew install fastlane` or `gem install fastlane`.",
  );
}
