export interface ModelField {
  name: string;
  type: "string" | "number" | "boolean" | "date" | "json" | "enum" | "relation";
  required?: boolean;
  editable?: boolean;
  enumValues?: string[];
  relationModel?: string;
  isArray?: boolean;
  hidden?: boolean;
}

export interface ModelConfig {
  name: string;
  plural: string;
  apiPath: string;
  icon: string;
  fields: ModelField[];
  displayField: string;
  category: string;
}

export const modelConfigs: ModelConfig[] = [
  {
    name: "User",
    plural: "Users",
    apiPath: "user",
    icon: "users",
    category: "Users & Teams",
    displayField: "email",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "email", type: "string", required: true },
      { name: "name", type: "string" },
      { name: "role", type: "enum", enumValues: ["ADMIN", "USER"], required: true },
      { name: "createdAt", type: "date", editable: false },
      { name: "updatedAt", type: "date", editable: false },
    ],
  },
  {
    name: "Team",
    plural: "Teams",
    apiPath: "team",
    icon: "building",
    category: "Users & Teams",
    displayField: "name",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "name", type: "string", required: true },
      { name: "createdAt", type: "date", editable: false },
      { name: "updatedAt", type: "date", editable: false },
    ],
  },
  {
    name: "TeamMember",
    plural: "Team Members",
    apiPath: "teamMember",
    icon: "user-check",
    category: "Users & Teams",
    displayField: "id",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "teamId", type: "string", required: true },
      { name: "userId", type: "string", required: true },
      { name: "role", type: "enum", enumValues: ["OWNER", "ADMIN", "MEMBER", "VIEWER"], required: true },
      { name: "createdAt", type: "date", editable: false },
    ],
  },
  {
    name: "TeamInvite",
    plural: "Team Invites",
    apiPath: "teamInvite",
    icon: "mail",
    category: "Users & Teams",
    displayField: "email",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "teamId", type: "string", required: true },
      { name: "email", type: "string", required: true },
      { name: "role", type: "enum", enumValues: ["OWNER", "ADMIN", "MEMBER", "VIEWER"] },
      { name: "token", type: "string", editable: false },
      { name: "invitedBy", type: "string", required: true },
      { name: "expiresAt", type: "date" },
      { name: "acceptedAt", type: "date" },
      { name: "createdAt", type: "date", editable: false },
    ],
  },
  {
    name: "TeamSettings",
    plural: "Team Settings",
    apiPath: "teamSettings",
    icon: "settings",
    category: "Users & Teams",
    displayField: "teamId",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "teamId", type: "string", required: true },
      { name: "ascIssuerId", type: "string" },
      { name: "ascKeyId", type: "string" },
      { name: "openaiApiKey", type: "string" },
      { name: "anthropicApiKey", type: "string" },
      { name: "aiProvider", type: "string" },
      { name: "mcpEnabled", type: "boolean" },
      { name: "githubUsername", type: "string" },
      { name: "updatedAt", type: "date", editable: false },
    ],
  },
  {
    name: "App",
    plural: "Apps",
    apiPath: "app",
    icon: "smartphone",
    category: "Apps",
    displayField: "name",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "bundleId", type: "string", required: true },
      { name: "name", type: "string", required: true },
      { name: "teamId", type: "string" },
      { name: "country", type: "string" },
      { name: "isOwnApp", type: "boolean" },
      { name: "currentTitle", type: "string" },
      { name: "currentSubtitle", type: "string" },
      { name: "currentKeywords", type: "string", hidden: true },
      { name: "githubRepoFullName", type: "string" },
      { name: "createdAt", type: "date", editable: false },
      { name: "updatedAt", type: "date", editable: false },
    ],
  },
  {
    name: "AppSnapshot",
    plural: "App Snapshots",
    apiPath: "appSnapshot",
    icon: "camera",
    category: "Apps",
    displayField: "title",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "appId", type: "string", required: true },
      { name: "title", type: "string", required: true },
      { name: "subtitle", type: "string" },
      { name: "description", type: "string", hidden: true },
      { name: "rating", type: "number" },
      { name: "ratingsCount", type: "number" },
      { name: "version", type: "string" },
      { name: "developerName", type: "string" },
      { name: "category", type: "string" },
      { name: "scrapedAt", type: "date", editable: false },
    ],
  },
  {
    name: "Keyword",
    plural: "Keywords",
    apiPath: "keyword",
    icon: "search",
    category: "ASO",
    displayField: "term",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "term", type: "string", required: true },
      { name: "country", type: "string" },
      { name: "language", type: "string" },
      { name: "popularity", type: "number" },
      { name: "difficulty", type: "number" },
      { name: "searchVolume", type: "number" },
      { name: "createdAt", type: "date", editable: false },
      { name: "updatedAt", type: "date", editable: false },
    ],
  },
  {
    name: "KeywordRanking",
    plural: "Keyword Rankings",
    apiPath: "keywordRanking",
    icon: "trending-up",
    category: "ASO",
    displayField: "id",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "keywordId", type: "string", required: true },
      { name: "appId", type: "string", required: true },
      { name: "rank", type: "number" },
      { name: "country", type: "string" },
      { name: "trackedAt", type: "date", editable: false },
    ],
  },
  {
    name: "ASOSuggestion",
    plural: "ASO Suggestions",
    apiPath: "asoSuggestion",
    icon: "lightbulb",
    category: "ASO",
    displayField: "type",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "type", type: "enum", enumValues: ["TITLE", "SUBTITLE", "KEYWORDS", "DESCRIPTION", "SCREENSHOT_ORDER"], required: true },
      { name: "locale", type: "string" },
      { name: "suggestedValue", type: "string", hidden: true },
      { name: "reasoning", type: "string", hidden: true },
      { name: "appBundleId", type: "string" },
      { name: "confidenceScore", type: "number" },
      { name: "status", type: "enum", enumValues: ["PENDING", "APPROVED", "APPLIED", "REJECTED", "EXPIRED"] },
      { name: "aiProvider", type: "string" },
      { name: "aiModel", type: "string" },
      { name: "createdAt", type: "date", editable: false },
    ],
  },
  {
    name: "AsoExperiment",
    plural: "ASO Experiments",
    apiPath: "asoExperiment",
    icon: "flask-conical",
    category: "ASO",
    displayField: "type",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "appId", type: "string", required: true },
      { name: "type", type: "enum", enumValues: ["KEYWORD_ADD", "KEYWORD_REMOVE", "KEYWORD_REPLACE", "TITLE_CHANGE", "SUBTITLE_CHANGE"] },
      { name: "fromValue", type: "string" },
      { name: "toValue", type: "string" },
      { name: "reason", type: "string", hidden: true },
      { name: "confidence", type: "number" },
      { name: "status", type: "enum", enumValues: ["PENDING", "APPROVED", "DEPLOYED", "EVALUATED", "REJECTED"] },
      { name: "createdAt", type: "date", editable: false },
    ],
  },
  {
    name: "CompetitorRelation",
    plural: "Competitor Relations",
    apiPath: "competitorRelation",
    icon: "swords",
    category: "Apps",
    displayField: "id",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "appId", type: "string", required: true },
      { name: "competitorId", type: "string", required: true },
      { name: "relevanceScore", type: "number" },
      { name: "addedAt", type: "date", editable: false },
    ],
  },
  {
    name: "AppStoreAnalytics",
    plural: "App Store Analytics",
    apiPath: "appStoreAnalytics",
    icon: "bar-chart-3",
    category: "Analytics",
    displayField: "bundleId",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "bundleId", type: "string", required: true },
      { name: "reportDate", type: "date" },
      { name: "country", type: "string" },
      { name: "downloads", type: "number" },
      { name: "impressions", type: "number" },
      { name: "pageViews", type: "number" },
      { name: "proceeds", type: "number" },
      { name: "createdAt", type: "date", editable: false },
    ],
  },
  {
    name: "AppReview",
    plural: "App Reviews",
    apiPath: "appReview",
    icon: "star",
    category: "Analytics",
    displayField: "title",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "ascReviewId", type: "string" },
      { name: "bundleId", type: "string", required: true },
      { name: "rating", type: "number", required: true },
      { name: "title", type: "string" },
      { name: "body", type: "string", hidden: true },
      { name: "reviewerNickname", type: "string" },
      { name: "territory", type: "string" },
      { name: "reviewedAt", type: "date" },
      { name: "createdAt", type: "date", editable: false },
    ],
  },
  {
    name: "CompetitorReview",
    plural: "Competitor Reviews",
    apiPath: "competitorReview",
    icon: "message-square",
    category: "Analytics",
    displayField: "id",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "appId", type: "string", required: true },
      { name: "rating", type: "number", required: true },
      { name: "title", type: "string" },
      { name: "body", type: "string", hidden: true },
      { name: "author", type: "string" },
      { name: "territory", type: "string" },
      { name: "reviewedAt", type: "date" },
      { name: "createdAt", type: "date", editable: false },
    ],
  },
  {
    name: "CompetitorReviewSummary",
    plural: "Review Summaries",
    apiPath: "competitorReviewSummary",
    icon: "message-square",
    category: "Analytics",
    displayField: "appId",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "appId", type: "string", required: true },
      { name: "reviewCount", type: "number" },
      { name: "averageRating", type: "number" },
      { name: "summary", type: "string", hidden: true },
      { name: "sentiment", type: "string" },
      { name: "aiProvider", type: "string" },
      { name: "aiModel", type: "string" },
      { name: "createdAt", type: "date", editable: false },
    ],
  },
  {
    name: "AppMetadataChange",
    plural: "Metadata Changes",
    apiPath: "appMetadataChange",
    icon: "file-diff",
    category: "Analytics",
    displayField: "field",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "appId", type: "string", required: true },
      { name: "field", type: "string", required: true },
      { name: "oldValue", type: "string", hidden: true },
      { name: "newValue", type: "string", hidden: true },
      { name: "detectedAt", type: "date", editable: false },
    ],
  },
  {
    name: "ScreenshotJob",
    plural: "Screenshot Jobs",
    apiPath: "screenshotJob",
    icon: "image",
    category: "Jobs (2)",
    displayField: "commitSha",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "appId", type: "string", required: true },
      { name: "commitSha", type: "string" },
      { name: "commitMessage", type: "string" },
      { name: "branch", type: "string" },
      { name: "status", type: "enum", enumValues: ["PENDING", "RUNNING", "COMPLETED", "FAILED"] },
      { name: "error", type: "string", hidden: true },
      { name: "startedAt", type: "date" },
      { name: "completedAt", type: "date" },
      { name: "createdAt", type: "date", editable: false },
    ],
  },
  {
    name: "BuildJob",
    plural: "Build Jobs",
    apiPath: "buildJob",
    icon: "hammer",
    category: "Jobs (2)",
    displayField: "id",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "appId", type: "string", required: true },
      { name: "branch", type: "string" },
      { name: "commitSha", type: "string" },
      { name: "status", type: "enum", enumValues: ["PENDING", "RUNNING", "COMPLETED", "FAILED"] },
      { name: "error", type: "string", hidden: true },
      { name: "startedAt", type: "date" },
      { name: "completedAt", type: "date" },
      { name: "createdAt", type: "date", editable: false },
    ],
  },
  {
    name: "OAuthClient",
    plural: "OAuth Clients",
    apiPath: "oauthClient",
    icon: "key",
    category: "System",
    displayField: "name",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "clientId", type: "string", required: true },
      { name: "clientSecret", type: "string", required: true },
      { name: "name", type: "string", required: true },
      { name: "userId", type: "string" },
      { name: "redirectUris", type: "json" },
      { name: "createdAt", type: "date", editable: false },
    ],
  },
  {
    name: "DeviceToken",
    plural: "Device Tokens",
    apiPath: "deviceToken",
    icon: "bell",
    category: "System",
    displayField: "token",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "token", type: "string", required: true },
      { name: "userId", type: "string" },
      { name: "bundleId", type: "string" },
      { name: "platform", type: "string" },
      { name: "isActive", type: "boolean" },
      { name: "createdAt", type: "date", editable: false },
    ],
  },
  {
    name: "PushNotificationLog",
    plural: "Push Notification Logs",
    apiPath: "pushNotificationLog",
    icon: "send",
    category: "System",
    displayField: "title",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "deviceToken", type: "string" },
      { name: "title", type: "string" },
      { name: "body", type: "string" },
      { name: "category", type: "string" },
      { name: "status", type: "string" },
      { name: "error", type: "string" },
      { name: "sentAt", type: "date", editable: false },
    ],
  },
  {
    name: "PasskeyCredential",
    plural: "Passkey Credentials",
    apiPath: "passkeyCredential",
    icon: "fingerprint",
    category: "Users & Teams",
    displayField: "id",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "userId", type: "string", required: true },
      { name: "credentialId", type: "string", editable: false },
      { name: "deviceType", type: "string" },
      { name: "backedUp", type: "boolean" },
      { name: "name", type: "string" },
      { name: "createdAt", type: "date", editable: false },
      { name: "lastUsedAt", type: "date" },
    ],
  },
  {
    name: "AscRateLimit",
    plural: "ASC Rate Limits",
    apiPath: "ascRateLimit",
    icon: "gauge",
    category: "System",
    displayField: "teamId",
    fields: [
      { name: "id", type: "string", editable: false },
      { name: "teamId", type: "string", editable: false },
      { name: "hourLimit", type: "number", editable: false },
      { name: "hourRemaining", type: "number", editable: false },
      { name: "updatedAt", type: "date", editable: false },
    ],
  },
];

export const modelCategories = [...new Set(modelConfigs.map((m) => m.category))];

export function getModelConfig(apiPath: string): ModelConfig | undefined {
  return modelConfigs.find((m) => m.apiPath === apiPath);
}
