import { Router, Request, Response } from "express";
import fs from "fs";
import path from "path";
import os from "os";
import { findFastlane } from "../fastlane-utils";
import { execAsync } from "./shared";

export const snapshotRouter = Router();

interface SnapshotRequest {
  repoUrl: string;
  accessToken: string;
  branch?: string;
  appName: string;
  bundleId: string;
  exportMethod?: string;
}

const DEFAULT_LANGUAGES = ["en-US"];
const DEFAULT_DEVICES = [
  "iPhone 16 Pro Max",
  "iPhone 16",
  "iPhone SE (3rd generation)",
  "iPad Pro 13-inch (M4)",
];

function findConfigFile(dir: string): string | null {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith(".") || entry.name === "fastlane") continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      const found = findConfigFile(full);
      if (found) return found;
    } else if (entry.name === "config.json") {
      return full;
    }
  }
  return null;
}

snapshotRouter.post("/snapshot", async (req: Request, res: Response) => {
  const body = req.body as SnapshotRequest;
  const { repoUrl, accessToken, branch, appName, bundleId } = body;

  if (!repoUrl || !accessToken) {
    res.status(400).json({ error: "Missing required fields" });
    return;
  }

  const tmpDir = path.join(os.tmpdir(), `worker-snapshot-${Date.now()}`);
  const logs: string[] = [];
  const errors: string[] = [];

  try {
    fs.mkdirSync(tmpDir, { recursive: true });

    const cloneUrl = repoUrl.replace(
      "https://",
      `https://x-access-token:${accessToken}@`,
    );

    const branchArg = branch ? `--branch ${branch}` : "";
    logs.push(`Cloning repo ${branch ? ` @${branch}` : ""} ...`);

    await execAsync(
      `git clone --depth 1 ${branchArg} "${cloneUrl}" "${tmpDir}"`,
      { timeout: 120_000 },
    );

    logs.push("Clone complete");

    let descriptions: Record<string, string> = {};
    let frameConfig: Record<string, string> = {};
    let scheme = appName;
    let effectiveDevices = DEFAULT_DEVICES;
    let effectiveLanguages = DEFAULT_LANGUAGES;

    const configFile = findConfigFile(tmpDir);
    if (configFile) {
      try {
        const parsed = JSON.parse(fs.readFileSync(configFile, "utf8"));
        const cfg = parsed._config ?? {};
        if (cfg.scheme) scheme = cfg.scheme;
        if (Array.isArray(cfg.devices) && cfg.devices.length)
          effectiveDevices = cfg.devices;
        if (Array.isArray(cfg.languages) && cfg.languages.length)
          effectiveLanguages = cfg.languages;
        if (cfg.bgColor1 || cfg.bgColor2 || cfg.textColor) {
          frameConfig = {
            bgColor1: cfg.bgColor1,
            bgColor2: cfg.bgColor2,
            textColor: cfg.textColor,
          };
        }
        const { _config: _, ...rest } = parsed;
        descriptions = rest;
        logs.push(
          `Loaded config.json from ${path.relative(tmpDir, configFile)} — scheme: ${scheme}, devices: ${effectiveDevices.join(", ")}, languages: ${effectiveLanguages.join(", ")}, ${Object.keys(descriptions).length} description(s)`,
        );
      } catch {
        logs.push(
          `Warning: could not parse ${path.relative(tmpDir, configFile)}`,
        );
      }
    } else {
      logs.push(
        `No config.json found — using defaults (scheme: ${scheme}, devices: ${effectiveDevices.join(", ")})`,
      );
    }

    const fastlaneDir = path.join(tmpDir, "fastlane");
    fs.mkdirSync(fastlaneDir, { recursive: true });
    fs.writeFileSync(
      path.join(fastlaneDir, "Snapfile"),
      [
        "# Auto-generated by AppCore Worker",
        `# App: ${appName} (${bundleId})`,
        "",
        "devices([",
        ...effectiveDevices.map((d) => `  "${d}",`),
        "])",
        "",
        `languages([${effectiveLanguages.map((l) => `"${l}"`).join(", ")}])`,
        "",
        `scheme("${scheme}")`,
        "",
        "clear_previous_screenshots(true)",
        'output_directory("./fastlane/screenshots")',
        "",
        "concurrent_simulators(true)",
        "",
      ].join("\n"),
    );

const fastlanePath = await findFastlane();
    logs.push(`Using fastlane: ${fastlanePath}\nRunning fastlane snapshot ...`);

    try {
      const { stdout, stderr } = await execAsync(
        `${fastlanePath} snapshot 2>&1`,
        {
          cwd: tmpDir,
          timeout: 900_000,
          env: { ...process.env, FASTLANE_DISABLE_COLORS: "1" },
          maxBuffer: 10 * 1024 * 1024,
        },
      );
      if (stdout) logs.push(...stdout.split("\n").filter(Boolean));
      if (stderr)
        logs.push(
          ...stderr
            .split("\n")
            .filter(Boolean)
            .map((l) => `[stderr] ${l}`),
        );
    } catch (execErr: any) {
      if (execErr.stdout)
        logs.push(...execErr.stdout.split("\n").filter(Boolean));
      if (execErr.stderr)
        logs.push(...execErr.stderr.split("\n").filter(Boolean));
      throw new Error(
        `fastlane snapshot exited with code ${execErr.code ?? "unknown"}.`,
      );
    }

    logs.push("fastlane snapshot completed");

    const screenshotsDir = path.join(tmpDir, "fastlane", "screenshots");
    const screenshots: Record<
      string,
      Array<{ filename: string; data: string }>
    > = {};

    if (fs.existsSync(screenshotsDir)) {
      const collectImages = (dir: string, locale: string) => {
        for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
          const full = path.join(dir, entry.name);
          if (entry.isDirectory()) {
            collectImages(full, entry.name);
          } else if (/\.(png|jpg|jpeg)$/i.test(entry.name)) {
            if (!screenshots[locale]) screenshots[locale] = [];
            const data = fs.readFileSync(full).toString("base64");
            screenshots[locale].push({ filename: entry.name, data });
          }
        }
      };
      collectImages(screenshotsDir, "default");
      const totalFiles = Object.values(screenshots).reduce(
        (n, a) => n + a.length,
        0,
      );
      logs.push(
        `Collected ${totalFiles} screenshot(s) across ${Object.keys(screenshots).length} locale(s)`,
      );
    } else {
      logs.push("No screenshots directory found after run");
    }

    res.json({
      ok: true,
      logs,
      errors,
      screenshots,
      descriptions,
      config: frameConfig,
    });
  } catch (err: any) {
    errors.push(err.message);
    res.json({ ok: false, logs, errors, screenshots: {} });
  } finally {
    try {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    } catch {
      // ignore
    }
  }
});
