export const COUNTRY_LANG: Record<string, string> = {
  ae: "ar",
  ao: "pt",
  ar: "es",
  at: "de",
  au: "en",
  be: "fr",
  bg: "bg",
  bh: "ar",
  bn: "ms",
  bo: "es",
  br: "pt",
  by: "ru",
  ca: "en",
  ch: "de",
  cl: "es",
  cn: "zh",
  co: "es",
  cr: "es",
  cy: "el",
  cz: "cs",
  de: "de",
  dk: "da",
  dz: "ar",
  ec: "es",
  ee: "et",
  eg: "ar",
  es: "es",
  fi: "fi",
  fr: "fr",
  gb: "en",
  gh: "en",
  gr: "el",
  gt: "es",
  hk: "zh",
  hn: "es",
  hr: "hr",
  hu: "hu",
  id: "id",
  ie: "en",
  il: "he",
  in: "hi",
  is: "is",
  it: "it",
  jm: "en",
  jo: "ar",
  jp: "ja",
  ke: "en",
  kr: "ko",
  kw: "ar",
  lb: "ar",
  lk: "en",
  lt: "lt",
  lu: "fr",
  lv: "lv",
  mg: "fr",
  mk: "mk",
  ml: "fr",
  mo: "zh",
  mt: "en",
  mu: "fr",
  mx: "es",
  my: "ms",
  ne: "fr",
  ng: "en",
  nl: "nl",
  no: "no",
  nz: "en",
  om: "ar",
  pa: "es",
  pe: "es",
  ph: "en",
  pk: "en",
  pl: "pl",
  pt: "pt",
  qa: "ar",
  ro: "ro",
  ru: "ru",
  sa: "ar",
  se: "sv",
  sg: "en",
  si: "sl",
  sk: "sk",
  sn: "fr",
  sr: "nl",
  sv: "es",
  th: "th",
  tn: "ar",
  tr: "tr",
  tw: "zh",
  tz: "en",
  ua: "uk",
  ug: "en",
  us: "en",
  uy: "es",
  ve: "es",
  vn: "vi",
  ye: "ar",
  za: "en",
};

export interface LocaleConfig {
  locale: string;
  language: string;
  promptLang: string;
  market: string;
  ollamaModel?: string;
}

export const LOCALE_MAP: Record<string, LocaleConfig> = {
  "en-US": {
    locale: "en-US",
    language: "English",
    promptLang: "English",
    market: "US/English-speaking",
    ollamaModel: "llama3.1:8b",
  },
  "en-GB": {
    locale: "en-GB",
    language: "English (UK)",
    promptLang: "English",
    market: "UK",
    ollamaModel: "llama3.1:8b",
  },
  "en-AU": {
    locale: "en-AU",
    language: "English (AU)",
    promptLang: "English",
    market: "Australian",
    ollamaModel: "llama3.1:8b",
  },
  "de-DE": {
    locale: "de-DE",
    language: "Deutsch",
    promptLang: "German",
    market: "German",
    ollamaModel: "gemma2:9b",
  },
  "fr-FR": {
    locale: "fr-FR",
    language: "Français",
    promptLang: "French",
    market: "French",
    ollamaModel: "gemma2:9b",
  },
  "es-ES": {
    locale: "es-ES",
    language: "Español",
    promptLang: "Spanish",
    market: "Spanish",
    ollamaModel: "gemma2:9b",
  },
  "es-MX": {
    locale: "es-MX",
    language: "Español (MX)",
    promptLang: "Spanish",
    market: "Latin American",
    ollamaModel: "gemma2:9b",
  },
  it: {
    locale: "it",
    language: "Italiano",
    promptLang: "Italian",
    market: "Italian",
    ollamaModel: "gemma2:9b",
  },
  "pt-BR": {
    locale: "pt-BR",
    language: "Português (BR)",
    promptLang: "Portuguese",
    market: "Brazilian",
    ollamaModel: "gemma2:9b",
  },
  "pt-PT": {
    locale: "pt-PT",
    language: "Português",
    promptLang: "Portuguese",
    market: "Portuguese",
    ollamaModel: "gemma2:9b",
  },
  "nl-NL": {
    locale: "nl-NL",
    language: "Nederlands",
    promptLang: "Dutch",
    market: "Dutch",
    ollamaModel: "gemma2:9b",
  },
  ja: {
    locale: "ja",
    language: "日本語",
    promptLang: "Japanese",
    market: "Japanese",
    ollamaModel: "qwen2.5:7b",
  },
  ko: {
    locale: "ko",
    language: "한국어",
    promptLang: "Korean",
    market: "Korean",
    ollamaModel: "qwen2.5:7b",
  },
  "zh-Hans": {
    locale: "zh-Hans",
    language: "中文(简体)",
    promptLang: "Simplified Chinese",
    market: "Chinese",
    ollamaModel: "qwen2.5:7b",
  },
  "zh-Hant": {
    locale: "zh-Hant",
    language: "中文(繁體)",
    promptLang: "Traditional Chinese",
    market: "Taiwanese/Hong Kong",
    ollamaModel: "qwen2.5:7b",
  },
  ru: {
    locale: "ru",
    language: "Русский",
    promptLang: "Russian",
    market: "Russian",
    ollamaModel: "gemma2:9b",
  },
  tr: {
    locale: "tr",
    language: "Türkçe",
    promptLang: "Turkish",
    market: "Turkish",
    ollamaModel: "gemma2:9b",
  },
  "ar-SA": {
    locale: "ar-SA",
    language: "العربية",
    promptLang: "Arabic",
    market: "Arabic-speaking",
    ollamaModel: "qwen2.5:7b",
  },
  th: {
    locale: "th",
    language: "ไทย",
    promptLang: "Thai",
    market: "Thai",
    ollamaModel: "qwen2.5:7b",
  },
  sv: {
    locale: "sv",
    language: "Svenska",
    promptLang: "Swedish",
    market: "Swedish",
    ollamaModel: "gemma2:9b",
  },
  da: {
    locale: "da",
    language: "Dansk",
    promptLang: "Danish",
    market: "Danish",
    ollamaModel: "gemma2:9b",
  },
  fi: {
    locale: "fi",
    language: "Suomi",
    promptLang: "Finnish",
    market: "Finnish",
    ollamaModel: "gemma2:9b",
  },
  no: {
    locale: "no",
    language: "Norsk",
    promptLang: "Norwegian",
    market: "Norwegian",
    ollamaModel: "gemma2:9b",
  },
  pl: {
    locale: "pl",
    language: "Polski",
    promptLang: "Polish",
    market: "Polish",
    ollamaModel: "gemma2:9b",
  },
  cs: {
    locale: "cs",
    language: "Čeština",
    promptLang: "Czech",
    market: "Czech",
    ollamaModel: "gemma2:9b",
  },
  el: {
    locale: "el",
    language: "Ελληνικά",
    promptLang: "Greek",
    market: "Greek",
    ollamaModel: "gemma2:9b",
  },
  he: {
    locale: "he",
    language: "עברית",
    promptLang: "Hebrew",
    market: "Israeli",
    ollamaModel: "gemma2:9b",
  },
  id: {
    locale: "id",
    language: "Bahasa Indonesia",
    promptLang: "Indonesian",
    market: "Indonesian",
    ollamaModel: "qwen2.5:7b",
  },
  ms: {
    locale: "ms",
    language: "Bahasa Melayu",
    promptLang: "Malay",
    market: "Malaysian",
    ollamaModel: "qwen2.5:7b",
  },
  vi: {
    locale: "vi",
    language: "Tiếng Việt",
    promptLang: "Vietnamese",
    market: "Vietnamese",
    ollamaModel: "qwen2.5:7b",
  },
  uk: {
    locale: "uk",
    language: "Українська",
    promptLang: "Ukrainian",
    market: "Ukrainian",
    ollamaModel: "gemma2:9b",
  },
  ro: {
    locale: "ro",
    language: "Română",
    promptLang: "Romanian",
    market: "Romanian",
    ollamaModel: "gemma2:9b",
  },
  hu: {
    locale: "hu",
    language: "Magyar",
    promptLang: "Hungarian",
    market: "Hungarian",
    ollamaModel: "gemma2:9b",
  },
  sk: {
    locale: "sk",
    language: "Slovenčina",
    promptLang: "Slovak",
    market: "Slovak",
    ollamaModel: "gemma2:9b",
  },
  hr: {
    locale: "hr",
    language: "Hrvatski",
    promptLang: "Croatian",
    market: "Croatian",
    ollamaModel: "gemma2:9b",
  },
  ca: {
    locale: "ca",
    language: "Català",
    promptLang: "Catalan",
    market: "Catalan",
    ollamaModel: "gemma2:9b",
  },
  hi: {
    locale: "hi",
    language: "हिन्दी",
    promptLang: "Hindi",
    market: "Indian",
    ollamaModel: "qwen2.5:7b",
  },
  "bn-BD": {
    locale: "bn-BD",
    language: "বাংলা",
    promptLang: "Bengali",
    market: "Bangladeshi",
    ollamaModel: "qwen2.5:7b",
  },
  "en-CA": {
    locale: "en-CA",
    language: "English (CA)",
    promptLang: "English",
    market: "Canadian",
    ollamaModel: "llama3.1:8b",
  },
  "fr-CA": {
    locale: "fr-CA",
    language: "Français (CA)",
    promptLang: "French",
    market: "Canadian French",
    ollamaModel: "gemma2:9b",
  },
  "gu-IN": {
    locale: "gu-IN",
    language: "ગુજરાતી",
    promptLang: "Gujarati",
    market: "Indian",
    ollamaModel: "qwen2.5:7b",
  },
  "kn-IN": {
    locale: "kn-IN",
    language: "ಕನ್ನಡ",
    promptLang: "Kannada",
    market: "Indian",
    ollamaModel: "qwen2.5:7b",
  },
  "ml-IN": {
    locale: "ml-IN",
    language: "മലയാളം",
    promptLang: "Malayalam",
    market: "Indian",
    ollamaModel: "qwen2.5:7b",
  },
  "mr-IN": {
    locale: "mr-IN",
    language: "मराठी",
    promptLang: "Marathi",
    market: "Indian",
    ollamaModel: "qwen2.5:7b",
  },
  "or-IN": {
    locale: "or-IN",
    language: "ଓଡ଼ିଆ",
    promptLang: "Odia",
    market: "Indian",
    ollamaModel: "qwen2.5:7b",
  },
  "pa-IN": {
    locale: "pa-IN",
    language: "ਪੰਜਾਬੀ",
    promptLang: "Punjabi",
    market: "Indian",
    ollamaModel: "qwen2.5:7b",
  },
  "sl-SI": {
    locale: "sl-SI",
    language: "Slovenščina",
    promptLang: "Slovenian",
    market: "Slovenian",
    ollamaModel: "gemma2:9b",
  },
  "ta-IN": {
    locale: "ta-IN",
    language: "தமிழ்",
    promptLang: "Tamil",
    market: "Indian",
    ollamaModel: "qwen2.5:7b",
  },
  "te-IN": {
    locale: "te-IN",
    language: "తెలుగు",
    promptLang: "Telugu",
    market: "Indian",
    ollamaModel: "qwen2.5:7b",
  },
  "ur-PK": {
    locale: "ur-PK",
    language: "اردو",
    promptLang: "Urdu",
    market: "Pakistani",
    ollamaModel: "qwen2.5:7b",
  },
};

const LOCALE_MAP_LOWERCASE = new Map(Object.keys(LOCALE_MAP).map((locale) => [locale.toLowerCase(), locale]));

export function normalizeLocale(locale: string): string | null {
  return LOCALE_MAP_LOWERCASE.get(locale.toLowerCase()) ?? null;
}

export function isValidLocale(locale: string): boolean {
  return normalizeLocale(locale) !== null;
}
