export const COUNTRY_LANG: Record<string, string> = {
  ae: "ar",
  ao: "pt",
  ar: "es",
  at: "de",
  au: "en",
  be: "fr",
  bg: "bg",
  bh: "ar",
  bn: "ms",
  bo: "es",
  br: "pt",
  by: "ru",
  ca: "en",
  ch: "de",
  cl: "es",
  cn: "zh",
  co: "es",
  cr: "es",
  cy: "el",
  cz: "cs",
  de: "de",
  dk: "da",
  dz: "ar",
  ec: "es",
  ee: "et",
  eg: "ar",
  es: "es",
  fi: "fi",
  fr: "fr",
  gb: "en",
  gh: "en",
  gr: "el",
  gt: "es",
  hk: "zh",
  hn: "es",
  hr: "hr",
  hu: "hu",
  id: "id",
  ie: "en",
  il: "he",
  in: "hi",
  is: "is",
  it: "it",
  jm: "en",
  jo: "ar",
  jp: "ja",
  ke: "en",
  kr: "ko",
  kw: "ar",
  lb: "ar",
  lk: "en",
  lt: "lt",
  lu: "fr",
  lv: "lv",
  mg: "fr",
  mk: "mk",
  ml: "fr",
  mo: "zh",
  mt: "en",
  mu: "fr",
  mx: "es",
  my: "ms",
  ne: "fr",
  ng: "en",
  nl: "nl",
  no: "no",
  nz: "en",
  om: "ar",
  pa: "es",
  pe: "es",
  ph: "en",
  pk: "en",
  pl: "pl",
  pt: "pt",
  qa: "ar",
  ro: "ro",
  ru: "ru",
  sa: "ar",
  se: "sv",
  sg: "en",
  si: "sl",
  sk: "sk",
  sn: "fr",
  sr: "nl",
  sv: "es",
  th: "th",
  tn: "ar",
  tr: "tr",
  tw: "zh",
  tz: "en",
  ua: "uk",
  ug: "en",
  us: "en",
  uy: "es",
  ve: "es",
  vn: "vi",
  ye: "ar",
  za: "en",
};

export const FASTLANE_LOCALE: Record<string, string> = {
  "en-US": "en-US",
  "en-GB": "en-GB",
  "en-AU": "en-AU",
  "en-CA": "en-CA",
  "de-DE": "de-DE",
  "fr-FR": "fr-FR",
  "es-ES": "es-ES",
  "es-MX": "es-MX",
  it: "it",
  "pt-BR": "pt-BR",
  "pt-PT": "pt-PT",
  ja: "ja",
  ko: "ko",
  "zh-Hans": "zh-Hans",
  "zh-Hant": "zh-Hant",
  "nl-NL": "nl-NL",
  ru: "ru",
  tr: "tr",
  "ar-SA": "ar-SA",
  th: "th",
  vi: "vi",
  id: "id",
  ms: "ms",
  sv: "sv",
  da: "da",
  fi: "fi",
  nb: "nb",
  pl: "pl",
  cs: "cs",
  sk: "sk",
  uk: "uk",
  el: "el",
  ro: "ro",
  hu: "hu",
  hr: "hr",
  ca: "ca",
  he: "he",
  hi: "hi",
};

export interface LocaleConfig {
  locale: string;
  language: string;
  promptLang: string;
  market: string;
}

export const LOCALE_MAP: Record<string, LocaleConfig> = {
  "en-US": {
    locale: "en-US",
    language: "English",
    promptLang: "English",
    market: "US/English-speaking",
  },
  "en-GB": {
    locale: "en-GB",
    language: "English (UK)",
    promptLang: "English",
    market: "UK",
  },
  "en-AU": {
    locale: "en-AU",
    language: "English (AU)",
    promptLang: "English",
    market: "Australian",
  },
  "de-DE": {
    locale: "de-DE",
    language: "Deutsch",
    promptLang: "German",
    market: "German",
  },
  "fr-FR": {
    locale: "fr-FR",
    language: "Français",
    promptLang: "French",
    market: "French",
  },
  "es-ES": {
    locale: "es-ES",
    language: "Español",
    promptLang: "Spanish",
    market: "Spanish",
  },
  "es-MX": {
    locale: "es-MX",
    language: "Español (MX)",
    promptLang: "Spanish",
    market: "Latin American",
  },
  "it-IT": {
    locale: "it-IT",
    language: "Italiano",
    promptLang: "Italian",
    market: "Italian",
  },
  "pt-BR": {
    locale: "pt-BR",
    language: "Português (BR)",
    promptLang: "Portuguese",
    market: "Brazilian",
  },
  "pt-PT": {
    locale: "pt-PT",
    language: "Português",
    promptLang: "Portuguese",
    market: "Portuguese",
  },
  "nl-NL": {
    locale: "nl-NL",
    language: "Nederlands",
    promptLang: "Dutch",
    market: "Dutch",
  },
  ja: {
    locale: "ja",
    language: "日本語",
    promptLang: "Japanese",
    market: "Japanese",
  },
  ko: {
    locale: "ko",
    language: "한국어",
    promptLang: "Korean",
    market: "Korean",
  },
  "zh-Hans": {
    locale: "zh-Hans",
    language: "中文(简体)",
    promptLang: "Simplified Chinese",
    market: "Chinese",
  },
  "zh-Hant": {
    locale: "zh-Hant",
    language: "中文(繁體)",
    promptLang: "Traditional Chinese",
    market: "Taiwanese/Hong Kong",
  },
  ru: {
    locale: "ru",
    language: "Русский",
    promptLang: "Russian",
    market: "Russian",
  },
  tr: {
    locale: "tr",
    language: "Türkçe",
    promptLang: "Turkish",
    market: "Turkish",
  },
  "ar-SA": {
    locale: "ar-SA",
    language: "العربية",
    promptLang: "Arabic",
    market: "Arabic-speaking",
  },
  th: { locale: "th", language: "ไทย", promptLang: "Thai", market: "Thai" },
  sv: {
    locale: "sv",
    language: "Svenska",
    promptLang: "Swedish",
    market: "Swedish",
  },
  da: {
    locale: "da",
    language: "Dansk",
    promptLang: "Danish",
    market: "Danish",
  },
  fi: {
    locale: "fi",
    language: "Suomi",
    promptLang: "Finnish",
    market: "Finnish",
  },
  nb: {
    locale: "nb",
    language: "Norsk",
    promptLang: "Norwegian",
    market: "Norwegian",
  },
  pl: {
    locale: "pl",
    language: "Polski",
    promptLang: "Polish",
    market: "Polish",
  },
  cs: {
    locale: "cs",
    language: "Čeština",
    promptLang: "Czech",
    market: "Czech",
  },
  el: {
    locale: "el",
    language: "Ελληνικά",
    promptLang: "Greek",
    market: "Greek",
  },
  he: {
    locale: "he",
    language: "עברית",
    promptLang: "Hebrew",
    market: "Israeli",
  },
  id: {
    locale: "id",
    language: "Bahasa Indonesia",
    promptLang: "Indonesian",
    market: "Indonesian",
  },
  ms: {
    locale: "ms",
    language: "Bahasa Melayu",
    promptLang: "Malay",
    market: "Malaysian",
  },
  vi: {
    locale: "vi",
    language: "Tiếng Việt",
    promptLang: "Vietnamese",
    market: "Vietnamese",
  },
  uk: {
    locale: "uk",
    language: "Українська",
    promptLang: "Ukrainian",
    market: "Ukrainian",
  },
  ro: {
    locale: "ro",
    language: "Română",
    promptLang: "Romanian",
    market: "Romanian",
  },
  hu: {
    locale: "hu",
    language: "Magyar",
    promptLang: "Hungarian",
    market: "Hungarian",
  },
  sk: {
    locale: "sk",
    language: "Slovenčina",
    promptLang: "Slovak",
    market: "Slovak",
  },
  hr: {
    locale: "hr",
    language: "Hrvatski",
    promptLang: "Croatian",
    market: "Croatian",
  },
  ca: {
    locale: "ca",
    language: "Català",
    promptLang: "Catalan",
    market: "Catalan",
  },
  hi: {
    locale: "hi",
    language: "हिन्दी",
    promptLang: "Hindi",
    market: "Indian",
  },
};
